"""
Morris Number (Look-and-Say) Generator

This module provides functionality to compute and display terms in the 
Morris number sequence, also known as the look-and-say sequence. Each term 
is generated by reading off the digits of the previous term, counting the 
number of digits in groups of the same digit.

Example sequence:
1, 11, 21, 1211, 111221, ...
"""

def morris_number(term):
    """
    Generates the nth term of the Morris number (look-and-say) sequence.
    """

    current = "1"

    for _ in range(1, term):
        next_term = ""
        index = 0

        while index < len(current):
            repeat = 1

            while index + repeat < len(current) and current[index + repeat] == current[index]:
                repeat += 1

            next_term += str(repeat) + current[index]
            index += repeat

        current = next_term

    return print(current)

if __name__ == "__main__":
    num = int(input("What term of the Morris Number Sequence do you want to print? "))
    morris_number(num)
